### PR TITLE
Add output_type_id_datatype property to v3.0.1. Resolves #87

### LINKED ISSUE #87: Introduce a property to fix the `output_type_id` column data type across the hub
## Background

For a hub to be successfully accessed as an arrow dataset, column data types should not change from round to round. 
Generally many task IDs that are covered by our schema shouldn't change data type in further rounds as that's somewhat fixed by the schema. Custom task IDs however, which are beyond our control, and the output_type_id column have the potential to change and this could indeed cause problems downstream. This is mainly a problem for parquet files (but has a small chance to cause problems in csvs too).

This is why early on when we had lots of discussions about this we allowed for a hub to override the automatic detection of the `output_type_id` data type in the `hubData::create_hub_schema()` function, used to determine the overall hub schema from the `tasks.json` config file.  To future proof the `output_type_id` admins could set the value of `output_type_id_datatype` to the  safest, most future proof data type, i.e. character.

## Set value of arg `output_type_id_datatype` in config

To enable hub admins to be able to configure and communicate this setting at a hub level, I propose an `output_type_id_datatype`  `enum` optional property at the top level of `tasks.json` config (i.e. sibling to  `rounds` and `schema_version`) that would accept valid `hubData::create_hub_schema()` `output_type_id_datatype` argument values. If this property exists in the config, the default behaviour (unless specifically overridden when calling) of `hubData::create_hub_schema()` would be to set the output type id column to the data type specified in the config.

This would give admins the ability to future proof their hubs by setting the column to character if they are unsure whether they may start collecting an output type that could affect the schema.

### PR DESCRIPTION
**Pull request by annakrystalli**
This PR introduces an optional `output_type_id_datatype` property to enable hub administrators to configure and communicate the `output_type_id` column data type at a hub level. This will allow hubs to override default behaviour of automatically determinining the simplest data type that can accomodate output type IDs across all output types when creating hub schema. 

The setting is also useful for administrators to future proof the `output_type_id` column from potential issues arising by changes in data type, introduced by new output types after submissions have begun, by setting `output_type_id_datatype` to the simplest data type from the start, i.e. character (#87).

For more info on related work see https://github.com/orgs/hubverse-org/projects/3/views/12

### CODE REVIEW

**Comment by zkamvar** [comment]
Not a review because I'm still swimming in the documentation sea, but here's a reference of the diff as of [0a93c9e](https://github.com/hubverse-org/schemas/pull/88/commits/0a93c9e268c3fb684e71a7798d78b67faab63f32)

```bash
diff -u --color=always v3.0.0/tasks-schema.json v3.0.1/tasks-schema.json
```

```diff
--- v3.0.0/tasks-schema.json	2024-07-22 08:47:15.851365031 -0700
+++ v3.0.1/tasks-schema.json	2024-07-22 08:47:36.079408585 -0700
@@ -1,6 +1,6 @@
 {
     "$schema": "https://json-schema.org/draft/2020-12/schema",
-    "$id": "https://raw.githubusercontent.com/hubverse-org/schemas/main/v3.0.0/tasks-schema.json",
+    "$id": "https://raw.githubusercontent.com/hubverse-org/schemas/main/v3.0.1/tasks-schema.json",
     "title": "Schema for Modeling Hub model task definitions",
     "description": "This is the schema of the tasks.json configuration file that defines the tasks within a modeling hub.",
     "type": "object",
@@ -1439,6 +1439,18 @@
                 ],
                 "additionalProperties": true
             }
+        },
+        "output_type_id_datatype": {
+            "description": "The hub level data type of the output_type_id column.",
+            "examples": ["character"],
+            "type": "string",
+            "enum": [
+                "character", 
+                "double", 
+                "integer",
+                "logical", 
+                "Date"
+            ]
         }
     },
     "required": [
```

**Comment by annakrystalli** [comment]
Thanks for the tip @zkamvar ! I reckon we should put that in the README as it's especially useful for these PRs

**Comment by annakrystalli** [comment]
Also I should mention that while the feature to override the column data type always existed in functions to create the schema it had not been exposed in the validations. This issue is the impetus for setting this work in action https://github.com/hubverse-org/hubValidations/issues/94

**Comment by LucieContamin** [comment]
> There's a link to additional related issues to this change in the PR description above and a lot more detail in the issue.

Thanks for the quick reply and sorry I was not clear, I got a little bit lost in all the links, that's why I was asking too. But my understanding is that it will be used in the function to create the schema, validate the schema (of course), validate the PR and submission and validate the model output, with that new optional parameter as default. Is that correct?  
I need to maybe think a little bit more, but I am little confused by this behavior of a optional parameter being the default of other function. 

> Also, this must be a hub level setting because all files, especially parquet must share the same schema to be opened as a dataset at a hub level.

That was my understanding for the hub level.

**Comment by annakrystalli** [comment]
Ah got it! 

If the parameter is not set, the rest of the functionality defaults to the previous default of autodetection. So no change to prior functionality if it's missing.

Hopefully all this will be clearer in the downstream PRs in the related packages.

**Review by nickreich — COMMENTED** [review]
I think the schema itself looks good, and I understand, based on the comments, why this is necessary. Maybe we could just add some more of the context to the description of the new optional field, like
```
       "output_type_id_datatype": {
           "description": "An optional specification at the hub-level of the simplest data type for the output_type_id column that can accommodate all data types for all model tasks. If not specified, downstream tasks such as validations will default to autodetecting the data type.",
```

**Comment by annakrystalli** [comment]
Thanks @nickreich & @LucieContamin for comments!
I've gone ahead and made the following changes (diff below):

- Added more detail to the property description. Note as well that I'm planning a whole section in hubDocs about the topic: https://github.com/hubverse-org/hubDocs/issues/143 
- I though about the property being optional too. We definitely want this to be optional because we don't want this change to be a breaking one (which it would be if we made it required). What I have done, though, is added an `"auto"` option. This is equivalent in behaviour to not including the property at all (i.e. when the property is missing, all downstream functionality defaults to `"auto"`), but it means we have a way to encode this default behaviour via a property value, which feels right to be possible. It also means we can include the property, set to the default `"auto"` in our `hubTemplate`, so new admins can be aware of it.
- I also added a note in the README with code snippets for producing file diffs between versions for easier reviewing.

```diff
--- v3.0.0/tasks-schema.json    2024-07-22 17:59:17
+++ v3.0.1/tasks-schema.json    2024-07-23 09:58:23
@@ -1,6 +1,6 @@
 {
     "$schema": "https://json-schema.org/draft/2020-12/schema",
-    "$id": "https://raw.githubusercontent.com/hubverse-org/schemas/main/v3.0.0/tasks-schema.json",
+    "$id": "https://raw.githubusercontent.com/hubverse-org/schemas/main/v3.0.1/tasks-schema.json",
     "title": "Schema for Modeling Hub model task definitions",
     "description": "This is the schema of the tasks.json configuration file that defines the tasks within a modeling hub.",
     "type": "object",
@@ -1439,6 +1439,20 @@
                 ],
                 "additionalProperties": true
             }
+        },
+        "output_type_id_datatype": {
+            "description": "The hub level data type of the output_type_id column. This data type must be shared across all files in the hub and be able to represent all output type ID values across all hub output types and rounds. If not provided, hub defaults to autodetecting the simplest hub level data type.",
+            "default": "auto",
+            "examples": ["character"],
+            "type": "string",
+            "enum": [
+                "auto",
+                "character", 
+                "double", 
+                "integer",
+                "logical", 
+                "Date"
+            ]
         }
     },
     "required": [
```

**Comment by annakrystalli** [comment]
Here's also a related PR in `hubTemplate` introducing the property but setting it to the previous `"auto"` behaviour by default: https://github.com/hubverse-org/hubTemplate/pull/17

**Comment by annakrystalli** [comment]
Also, in case you are interested in downstream implementation details @LucieContamin, I've now opened the first related PR in `hubData` https://github.com/hubverse-org/hubData/pull/49

**Review by nickreich — APPROVED** [review]
Thanks for the changes reflecting my suggestions.

**Pull request merged**
